### ISSUE TITLE
PNG not displaying on scrollback

### ISSUE THREAD

**Issue by Githarp** [Nyx0uf/qlImageSize#10]
It seems like when *thumbing* through PNG files, while *scrolling* through with my arrow keys or by mouse clicking, and if I were to *go back* to the image that I just looked at, the image will not be displayed but instead, a blank canvas with the photo's dimension will be displayed. On 10.10.2.

GIF for better illustration.

![png ql](https://cloud.githubusercontent.com/assets/3303398/6744879/ba64b708-cee9-11e4-93bf-f5bd050c2df1.gif)

Any idea what's going on?
Thanks!

PS: JPEGs work fine.

**Comment by Nyx0uf** [comment]
Can you try with a beta version of 10.10.3 ? Because I encountered some problems with 10.10.2 and QuickLook previews that are fixed with the beta version.

**Comment by Githarp** [comment]
Unfortunately, I'm experiencing this issue on a production Mac. I have a spare Mac, where I do beta testing on, and am unable to replicate the issue not have the issue with PNG files. 

However, it might be another program that I've installed which could be at fault here which is [Art View](http://www.code-line.com/blog/art-view-and-mac-os-x-10-10-2-update/). Will update once 10.10.3 comes around.

**Comment by c-wee** [comment]
10.10.3 came around and still am having the same issue.
Searched around and found that it is due to a quicklook text selection bug.

Followed the advice [here](https://apple.stackexchange.com/questions/128825/quicklook-blanks-when-displaying-some-images).

The only downside is that I now *can't* select text from quicklook. Inconvenient, but saves me from innumerable frustration.

**Comment by Nyx0uf** [comment]
So, can I close this issue ?

**Comment by c-wee** [comment]
Yes you may.
